name: Feature Request
description: Suggest an idea for this project
title: "[Feature request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in Swashbuckler Diary! We welcome any and all ideas for features or improvements that you might have.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please give us a detailed description of the feature that you envision. Focus on _what_ this feature does, over the _why_ you want this feature. What would be the end-result when implemented? Feel free to add any diagrams, (mocked up) screenshots, or other materials that support your story.
    validations:
      required: true
  - type: dropdown
    id: platforms-supported
    attributes:
      label: Supported platforms
      description: Select the platform that needs to be supported. If everything is needed, there is no need to choose
      multiple: true
      options:
        - Android
        - iOS
        - macOS
        - Web
        - Windows
  - type: textarea
    id: applications-with-this-feature
    attributes:
      label: Applications with this feature
      description: List the applications that have this feature, or display screenshots
  - type: textarea
    id: technologies-related
    attributes:
      label: Related technologies
      description: Recommend some technologies, components, and libraries related to this feature
